# _config.yml
title: Social Network Course
description: "Official website for the Social Network course at Tehran University."
author: "Tehran University, School of ECE"
collections:
  exercises:
    output: true
    permalink: /exercises/:title/